#!/bin/bash

EXPECTED="y0ur_fr1end1y_n3igh8ourh0od_sp1derman"

if [[ $# -ne 1 ]]; then
    echo "Usage: submit <answer>"
    exit 1
fi

ANSWER="$1"

echo
echo "================================"
echo "       LEVEL 3 SUBMISSION"
echo "================================"
echo

if [[ "$ANSWER" != "$EXPECTED" ]]; then
    echo "[!] Incorrect answer."
    echo "[!] Level 3 remains unchanged."
    exit 1
fi

echo "[+] Correct answer."
echo "[+] Level 3 completed."
echo

echo "[+] Cleaning up Level 3..." 

# Delete everything inside level1, including hidden files.
find $HOME \
-mindepth 1 \
-maxdepth 1 \
! -name ".bashrc" \
-exec rm -rf -- {} +

echo 'unalias submit' >> $HOME/.bashrc
source $HOME/.bashrc

echo "[+] Level 3 files removed."